### ISSUE TITLE
undefined balances set to `null` on initial claim ($bAR CONTRACT)

### ISSUE THREAD

**Issue by jshaw-decides** [t8/verto-flex-example#2]
Hello --

I'm raising an issue on the BAR contract: `mMffEC07TyoAFAI_O6q_nskj2bT8n4UFvckQ3yELeic`

There's a bug when setting a value of a balance in the `claim` function.

This is what exists:
<img width="639" alt="Screen Shot 2022-10-17 at 8 20 34 PM" src="https://user-images.githubusercontent.com/105590998/196313038-63f3dd92-c868-48e4-9a4a-88d41b114941.png">

`balances[caller] += obj.qty;` is the line of code that is having the issue.

If `balances[caller]` is not defined -> the balance will initially be set to `null` and the claim will be completed.

PROPOSED SOLUTION:

I'm proposing this as a quick fix -- as I'm not certain of the long term vision for contract.  If the contract continues to use "integers":

Replace :

`balances[caller] += obj.qty;`

with (i tested this one):

```
if (!Number.isInteger(balances[caller])) balances[caller] = 0;
balances[caller] += obj.qty;
```

or (i haven't tested this one):

```
balances[caller] ? balances[caller] += obj.qty : balances[caller] = obj.qty
```

Let me know if you need more info or if there's a better repo to submit this issue on!

- jshaw

**Comment by t8** [comment]
Hey jshaw, thanks for the detailed report here! Tested this on my end as well. I'll inform Vertoshi that a new deployment can be made.
